### ISSUE TITLE
Oh snap

### ISSUE THREAD

**Issue by ghost** [seletskiy/vim-over80#1]
![2016-05-02-162217_1920x1080_scrot](https://cloud.githubusercontent.com/assets/4725121/14956811/f447dd3a-1081-11e6-8589-d3a49188e940.png)

![2016-05-02-162406_1920x1080_scrot](https://cloud.githubusercontent.com/assets/4725121/14956812/f46a372c-1081-11e6-972e-f6b7fe4d8cd3.png)

The things become even more interesting when I have more splitted windows and **only** one of the splits has lines over 80 chars longs.

**Comment by seletskiy** [comment]
@wifiextender: Can you explain the issue? I do not understand, what is the problem on the screenshots?

**Comment by ghost** [comment]
I was expecting the highlighting to take place only at the line(s) that exceed the 80 chars limit and not the entire window.

The issue becomes even more obvious when there are splitted windows, as the current state of this plugin will highlight all the window (splits) as **exceeding** the 80 chars limit, while only one of them actually exceeds the limit.

A much more convinient approach to highlight the 80 chars limit would be like the following as showing in this picture ![](http://mixandgo.com/uploads/blog_image/image/28/emacs_whitespace_mode.png)

**Comment by ghost** [comment]
20 minutes later:  https://superuser.com/questions/249779/how-to-setup-a-line-length-marker-in-vim-gvim/249793#249793

![2016-05-03-080831_1920x1080_scrot](https://cloud.githubusercontent.com/assets/4725121/14975761/54c9f2aa-1105-11e6-958d-6cb991ce0b4a.png)

**Comment by seletskiy** [comment]
That type of highlighting was intentional. I like padded style editor space, so gray area looks like forbidden place, because my code never exceeds 80 chars limit. 

Proposed on the stackoverflow solution is bad, because reading of 3rd party's code becomes pain for the eyes and you lose syntax highlighting. 

Another solution is just specifying cc=80, has different problem: search highlighting will not work in that column. That is the reason why I wrote this plugin in the first place.
